// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnQjdx6iCGj6-ZKpJO3_BtF4WznGjxsGI',
    appId: '1:812292566794:web:bc61960dbe3a7eb03c14f3',
    messagingSenderId: '812292566794',
    projectId: 'mindease-focus',
    authDomain: 'mindease-focus.firebaseapp.com',
    storageBucket: 'mindease-focus.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnQjdx6iCGj6-ZKpJO3_BtF4WznGjxsGI',
    appId: '1:812292566794:web:bc61960dbe3a7eb03c14f3',
    messagingSenderId: '812292566794',
    projectId: 'mindease-focus',
    authDomain: 'mindease-focus.firebaseapp.com',
    storageBucket: 'mindease-focus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnQjdx6iCGj6-ZKpJO3_BtF4WznGjxsGI',
    appId: '1:812292566794:web:bc61960dbe3a7eb03c14f3',
    messagingSenderId: '812292566794',
    projectId: 'mindease-focus',
    authDomain: 'mindease-focus.firebaseapp.com',
    storageBucket: 'mindease-focus.firebasestorage.app',
    iosBundleId: 'com.mindease.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnQjdx6iCGj6-ZKpJO3_BtF4WznGjxsGI',
    appId: '1:812292566794:web:bc61960dbe3a7eb03c14f3',
    messagingSenderId: '812292566794',
    projectId: 'mindease-focus',
    authDomain: 'mindease-focus.firebaseapp.com',
    storageBucket: 'mindease-focus.firebasestorage.app',
    iosBundleId: 'com.mindease.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnQjdx6iCGj6-ZKpJO3_BtF4WznGjxsGI',
    appId: '1:812292566794:web:bc61960dbe3a7eb03c14f3',
    messagingSenderId: '812292566794',
    projectId: 'mindease-focus',
    authDomain: 'mindease-focus.firebaseapp.com',
    storageBucket: 'mindease-focus.firebasestorage.app',
  );
}
